Fall Game
Metroxe/one-html-page-challenge pull request #53
Opened 2021-05-02 07:05 UTC by SNEHAL311998

2021-05-03 20:04 UTC, Metroxe requested changes

2021-05-03 20:04 UTC, Metroxe commented on entries/fall_game.html
> +        @import url('https://fonts.googleapis.com/css2?family=Lobster+Two:ital,wght@1,700&display=swap');
As part of the rules you cannot...

```
- You cannot import any external files (this will be checked by looking at the network tab in chrome).
- Due to the nature of hiding lots of funtionality behind APIs, you cannot have any incoming network requests.
```

You must either encode the font as a base64 or not use it.

2021-05-04 02:03 UTC, SNEHAL311998 commented
I have removed the imports and font family. You may check my recent commit which says import removed

2021-05-04 15:52 UTC, Metroxe approved these changes

2021-05-04 15:53 UTC, Metroxe approved these changes

2021-05-04 15:53 UTC, Metroxe commented
Looks good! Thank you for the submission.

2021-05-04 15:53 UTC, merged