Character Counter
Metroxe/one-html-page-challenge pull request #57
Opened 2021-08-08 12:11 UTC by samiullahsaleem

![image](https://user-images.githubusercontent.com/54318487/128631380-55c8a60f-99d1-4886-8870-d818fa4a4156.png)
# 👋Hi! 
### My name is Sami Ullah Saleem. I have created this awesome page that can help to count your characters of yours. 
## How can you adjust styling?
* You can add font size in the font size box.
* You can add the background color of the character counter box. 
* You can add the font color in the font color box.  

#### I am hopeful you will like my project. 
## Wanna Connect  
[Facebook]("www.facebook.com/samiullah.saleem.5036")  
[Linkedin]("www.linkedin.com/in/samiullahsaleem/")
[Email]("samiullah1701734@gmail.com")

2021-08-09 23:21 UTC, kareen-art commented
I did not know the pull request ha went through. this is about paypal and having one html page for Paypal.

2021-08-10 17:23 UTC, Metroxe requested changes

2021-08-10 17:23 UTC, Metroxe commented on entries/character_counter.html
> +    <script src="https://unpkg.com/vue@3.0.7/dist/vue.global.js"></script>
Sorry this breaks the rules. Please see the README

"You cannot import any external files (this will be checked by looking at the network tab in chrome)."

2021-09-01 00:56 UTC, Metroxe commented
closed due to inactivity

2021-09-01 00:56 UTC, closed without merging