added tic-tac-toe game
Metroxe/one-html-page-challenge pull request #58
Opened 2021-09-03 14:14 UTC by Sumandeep-Kaur

### Added a simple Tic-Tac-Toe game.
Tic-tac-toe is a pencil and paper game on a 3x3 grid in which two players take turns alternatively in drawing either an 'O' or an 'X' in one of the square of a grid containing nine squares. The winner is the first player to get three of the same symbols in a line either in horizontal, vertical or diagonal.

2021-09-06 20:52 UTC, Metroxe requested changes

2021-09-06 20:52 UTC, Metroxe commented on entries/tic-tac-toe.html
> +        @import url('https://fonts.googleapis.com/css2?family=Uchen&display=swap');
Sorry there no external files allowed, you need to remove the font import

2021-09-07 07:51 UTC, Sumandeep-Kaur commented
Made the requested changes, please have a look!

2021-09-07 19:41 UTC, Metroxe approved these changes

2021-09-07 19:41 UTC, merged