ADD Screen Resolution Finder
Metroxe/one-html-page-challenge pull request #69
Opened 2021-12-04 15:12 UTC by 7ORP3DO

2021-12-07 23:12 UTC, Metroxe requested changes

2021-12-07 23:12 UTC, Metroxe commented on entries/my-screen-resolution.html
> +        @import url(https://fonts.googleapis.com/css?family=Exo+2:200i);
No outside API calls, sorry. You will need to remove adding the font in

2021-12-08 16:15 UTC, 7ORP3DO commented on entries/my-screen-resolution.html
> +        @import url(https://fonts.googleapis.com/css?family=Exo+2:200i);
@Metroxe Thanks your feedback 🙂.


I just made the requested changes, please have a look!

2021-12-08 19:39 UTC, Metroxe approved these changes

2021-12-08 19:39 UTC, merged

2021-12-08 19:39 UTC, Metroxe commented
Looks great! Thank you for your submission