Added Calculator
Metroxe/one-html-page-challenge pull request #79
Opened 2022-03-28 12:13 UTC by Abhay557

A Calculator Using Javascript For One Page Html Challenge! And Its Made In Only One Page! Sir @Metroxe

2022-03-28 12:55 UTC, TheTechRobo commented on entries/Calculator.html
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700&display=swap');
This is a page requisite, which IIRC is not allowed.

2022-03-28 12:55 UTC, TheTechRobo commented on entries/Calculator.html
> +    <link rel="stylesheet" href="style.css">
Same with this.

2022-03-28 15:58 UTC, Abhay557 commented on entries/Calculator.html
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700&display=swap');
Sir Let Owner Take decision!

2022-03-28 15:59 UTC, Abhay557 commented on entries/Calculator.html
> +    <link rel="stylesheet" href="style.css">
Not Be Rush With Your decision

2022-03-28 17:56 UTC, Metroxe commented on entries/Calculator.html
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700&display=swap');
@TheTechRobo is correct, you cannot import fonts from an external URL

2022-03-28 17:58 UTC, Metroxe requested changes

2022-03-28 17:58 UTC, Metroxe commented on entries/Calculator.html
> +    <link rel="stylesheet" href="style.css">
I'm not sure if this even works, but you should remove any import of files. You can embed the style in a `<style>` tag

2022-03-28 17:58 UTC, Metroxe commented on entries/Calculator.html
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700&display=swap');
You can actually use the base64 version of the fonts, since that doesn't require a network request.

2022-03-29 10:07 UTC, Abhay557 commented on entries/Calculator.html
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700&display=swap');
Ok Sir, I Have Updated The File And
Yes It Can Be Run Without Those Fonts.

2022-03-29 10:07 UTC, Abhay557 commented on entries/Calculator.html
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700&display=swap');
@Metroxe Please See Now ! I Mean Review The Changes

2022-03-29 10:10 UTC, Abhay557 commented on entries/Calculator.html
> +    <link rel="stylesheet" href="style.css">
Updated Please See Now

2022-03-29 18:33 UTC, merged