added blur-loading-page.html
Metroxe/one-html-page-challenge pull request #87
Opened 2022-07-31 18:47 UTC by nirban256

Added Blur loading of background transition.

2022-07-31 18:48 UTC, nirban256 commented
@Metroxe please review the pull request

2022-08-05 04:11 UTC, Metroxe requested changes

2022-08-05 04:11 UTC, Metroxe commented on entries/blur-loading-page.html
> +        background: url('https://images.unsplash.com/photo-1529619768328-e37af76c6fe5?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1287&q=80') no-repeat cen
You cannot use an external file, everything must be in one html file only. You can still use the image if its encoded as a base64 inline

2022-08-19 08:12 UTC, nirban256 commented on entries/blur-loading-page.html
> +        background: url('https://images.unsplash.com/photo-1529619768328-e37af76c6fe5?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1287&q=80') no-repeat cen
ok I will try to fix that

2022-08-30 08:22 UTC, nirban256 commented
@Metroxe I have changed the image with a static colour, review it once

2022-09-07 20:14 UTC, Metroxe approved these changes
looks good!

2022-09-07 20:14 UTC, merged