Submission for one-html-page-challenge, Build an online Stopwatch
Metroxe/one-html-page-challenge pull request #89
Opened 2022-08-01 06:46 UTC by sethkabir

2022-08-05 04:13 UTC, Metroxe requested changes

2022-08-05 04:13 UTC, Metroxe commented on entries/stopWatch.html
> +		<script src="https://cdn.tailwindcss.com"></script>
You cannot use any external files, so no importing tailwind

2022-08-05 11:54 UTC, sethkabir commented on entries/stopWatch.html
> +		<script src="https://cdn.tailwindcss.com"></script>
Removed tailwind and added pure css

2022-08-07 00:39 UTC, Metroxe approved these changes
thank you!

2022-08-07 00:39 UTC, merged