Water Wave Cup
Metroxe/one-html-page-challenge pull request #90
Opened 2022-08-01 07:23 UTC by satyasonu

I have created a cup which is filled with water and creating a wave. Please consider this as my submission. Here I have used simple HTML and CSS in it.
The below is page snapshot. Please check once.
![image](https://user-images.githubusercontent.com/64128421/182094654-1aa04523-842c-488e-93e1-b463590e2da6.png)

2022-08-05 04:14 UTC, Metroxe requested changes

2022-08-05 04:14 UTC, Metroxe commented on entries/cupWaterWave.html
> +        background: url(https://image.ibb.co/fmHm66/wave.png);
You cannot use an external image/file, if you want to use an image you will need to embed the image as a base64 inline.

2022-08-05 09:30 UTC, satyasonu commented
I have changed the external image link into **base64** inline. Please check my code.

2022-08-05 09:54 UTC, satyasonu commented on entries/cupWaterWave.html
> +        background: url(https://image.ibb.co/fmHm66/wave.png);
Thanks for the suggestion. I have changed external image file to base64 inline.

2022-08-07 00:36 UTC, Metroxe approved these changes

2022-08-07 00:36 UTC, Metroxe commented
all good, thank you!

2022-08-07 00:36 UTC, merged