Added my html file with changes in js .
Metroxe/one-html-page-challenge pull request #92
Opened 2022-08-01 14:36 UTC by IamGuneet

If everything goes well then this would be my first contribution, feels nice.

2022-08-05 04:18 UTC, Metroxe requested changes

2022-08-05 04:18 UTC, Metroxe commented on entries/Sidhumoosewala-tribute-page.html
> +            <img src="https://images.tv9hindi.com/wp-content/uploads/2022/04/controversy-on-sidhu-moosewala-song.jpg" alt="Moose" style="height: 140px; width: 240px; border-radius: 50%;">
Sorry, you will need to make this image an inline base64. Since you have only 1 html file to work with, you cannot import an external file/image.

2022-08-07 00:37 UTC, Metroxe approved these changes
All good, thank you!

2022-08-07 00:38 UTC, merged

2022-10-11 06:58 UTC, IamGuneet commented
Okay sure,
Thank you

On Fri, Aug 5, 2022, 9:48 AM Christopher Powroznik ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In entries/Sidhumoosewala-tribute-page.html
> <https://github.com/Metroxe/one-html-page-challenge/pull/92#discussion_r938427579>
> :
>
> > @@ -0,0 +1,44 @@
> +<!DOCTYPE html>
> +<html lang="en">
> +
> +<head>
> +    <meta charset="UTF-8">
> +    <meta http-equiv="X-UA-Compatible" content="IE=edge">
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
> +    <title>Rip Moose</title>
> +</head>
> +
> +<body style="background-color:rgb(155, 155, 233);color: rgb(0, 0, 0); padding: 20px; text-align: center; font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;">
> +    <div style="padding:10px 200px; border: 5px solid gold;border-radius: 20px;">
> +        <h1 style="color: azure; text-decoration:underline gold ;">R.I.P - Sidhu a.k.a Moosewala</h1>
> +            <img src="https://images.tv9hindi.com/wp-content/uploads/2022/04/controversy-on-sidhu-moosewala-song.jpg" alt="Moose" style="height: 140px; width: 240px; border-radius: 50%;">
>
> Sorry, you will need to make this image an inline base64. Since you have
> only 1 html file to work with, you cannot import an external file/image.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Metroxe/one-html-page-challenge/pull/92#pullrequestreview-1062822272>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZNWXKWGU35VMICVY3CY4DTVXSI2LANCNFSM55HZRQ5Q>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>