Tejash animating gradients
Metroxe/one-html-page-challenge pull request #95
Opened 2022-08-02 17:41 UTC by tejash023

2022-08-05 04:25 UTC, Metroxe requested changes

2022-08-05 04:25 UTC, Metroxe commented on entries/taskListApp.html
> +  <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
One of the rules is...

> You cannot import any external files (this will be checked by looking at the network tab in chrome).

Here you are importing 3 `.css` files. You will need to inline your styles.

2022-08-05 04:25 UTC, Metroxe commented on entries/taskListApp.html
> +  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
One of the rules is...

> You cannot import any external files (this will be checked by looking at the network tab in chrome).

Here you are importing 3 `.css` files. You will need to inline your styles.

2022-08-10 09:02 UTC, tejash023 commented on entries/taskListApp.html
> +  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
Hi removed all the dependencies and added my entry in entry.js

2022-08-11 06:38 UTC, Metroxe requested changes

2022-08-11 06:38 UTC, Metroxe commented on entries.js
> +	},
Your commit has 2 html files, so you would need two entries to add both

2022-08-11 06:38 UTC, Metroxe commented on entries/taskListApp.html
> +  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
These dependencies are still showing in your merge request

2022-08-11 06:38 UTC, Metroxe commented on entries/taskListApp.html
> +  <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
same with these

2022-08-11 06:41 UTC, Metroxe commented
I didn't realize you made 2 pull requests. I think you accidentally committed the same HTML in both. I will close this pull request, if you want to submit the second one, please open again.

2022-08-11 06:41 UTC, closed without merging